#! /bin/bash

# Check number of arguments
[[ ! ${#} -eq 1 ]] && \
echo -e "\e[1;31mERROR: incorrect number of arguments passed\e[0m" && \
echo "USAGE: asm.sh <ASSEMBLY_FILE>"

Fname=${1}
Pname=`echo ${1} | cut -d '.' -f1`

read -p "Maintain obejct file (.o) after compilation? (N)/y " objMa

as ${Fname} -o ${Pname}.o -g
ld ${Pname}.o -o ${Pname} -dynamic-linker /lib/x86_64-linux-gnu/ld-linux-x86-64.so.2 \
/usr/lib/crt1.o /usr/lib/crti.o \
/usr/lib/crtn.o -lc

[[ "${objMa}" != "y" ]] && [[ "${objMa}" != "Y" ]] && rm ${Pname}.o
